=== nikolaim665/XML-Group-Project/Customers.dtd
<!DOCTYPE Customers [
    <!ELEMENT Customers (Customer+)>
    <!ELEMENT Customer (User, email, tickets)>
    <!ELEMENT User (userId, username, password)>
    <!ATTLIST User
          userID ID #REQUIRED>
    <!ELEMENT username (#PCDATA)>
    <!ELEMENT password (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT tickets (ticket+)>
    <!ELEMENT ticket (ticketID)>
    <!ATTLIST ticket
          ticketID ID #REQUIRED>
]>

=== nikolaim665/XML-Group-Project/Customers.xml
<?xml version='1.0' encoding='utf-8' standalone="no"?>
<!DOCTYPE Customer SYSTEM "Customers.dtd">
<Customers>
    <Customer>
        <User>
            <userId>1</userId>
            <username>t2zb8afxox</username>
            <password>y76il9m1wa</password>
        </User>
        <email>t2zb8afxox@gmail.com</email>
        <tickets>
            <ticket>1</ticket>
            <ticket>2</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>2</userId>
            <username>zb9x9n37ph</username>
            <password>jx227zoxl6</password>
        </User>
        <email>zb9x9n37ph@gmail.com</email>
        <tickets>
            <ticket>3</ticket>
            <ticket>4</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>3</userId>
            <username>5jc6lx9969</username>
            <password>j6n56wkr4v</password>
        </User>
        <email>5jc6lx9969@gmail.com</email>
        <tickets>
            <ticket>5</ticket>
            <ticket>6</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>4</userId>
            <username>tizpcsplly</username>
            <password>fj1l5uuka9</password>
        </User>
        <email>tizpcsplly@gmail.com</email>
        <tickets>
            <ticket>7</ticket>
            <ticket>8</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>5</userId>
            <username>qo0rql4b7u</username>
            <password>l1x213g8iz</password>
        </User>
        <email>qo0rql4b7u@gmail.com</email>
        <tickets>
            <ticket>9</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>6</userId>
            <username>8rs6bch4j4</username>
            <password>pxjjk4j82l</password>
        </User>
        <email>8rs6bch4j4@gmail.com</email>
    </Customer>
    <Customer>
        <User>
            <userId>7</userId>
            <username>pfw5fbx8n6</username>
            <password>6jirpomqq5</password>
        </User>
        <email>pfw5fbx8n6@gmail.com</email>
        <tickets>
            <ticket>10</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>8</userId>
            <username>kb94ka6i2e</username>
            <password>qe54u09wuo</password>
        </User>
        <email>kb94ka6i2e@gmail.com</email>
    </Customer>
    <Customer>
        <User>
            <userId>9</userId>
            <username>ldaj027gd5</username>
            <password>0m1udyk0kb</password>
        </User>
        <email>ldaj027gd5@gmail.com</email>
        <tickets>
            <ticket>11</ticket>
        </tickets>
    </Customer>
    <Customer>
        <User>
            <userId>10</userId>
            <username>v888qvupse</username>
            <password>y9z35rudey</password>
        </User>
        <email>v888qvupse@gmail.com</email>
        <tickets>
            <ticket>12</ticket>
        </tickets>
    </Customer>
</Customers>
