=== nikolaim665/XML-Group-Project/Events.dtd
<!ELEMENT Events (Event+)>
<!ELEMENT Event (event_ID,venue,date,entertainer,tickets_available)>
<!ATTLIST Event
          event_ID ID #REQUIRED>
<!ELEMENT venue (venue)>
<!ATTLIST venue
          venue.id ID #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT entertainer (entertainer)>
<!ATTLIST entertainer
          entertainer_id ID #REQUIRED>
<!ELEMENT tickets_available (#PCDATA)>

=== nikolaim665/XML-Group-Project/Events.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE events SYSTEM "Events.dtd">
<Events>
    <Event>
        <event_ID>1</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>2</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>3</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>4</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>5</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>6</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>7</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>8</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>9</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
    <Event>
        <event_ID>10</event_ID>
        <venue>Los Angeles</venue>
        <date>21/11/2023</date>
        <entertainer>1</entertainer>
        <tickets_available>255</tickets_available>
    </Event>
</Events>
