=== nikolaim665/XML-Group-Project/Tickets.dtd
<!ELEMENT Tickets (Ticket+)>
<!ELEMENT Ticket (ticketID,event,customer)>
<!ELEMENT ticketID (#PCDATA)>
<!ELEMENT event (#PCDATA)>
<!ELEMENT customer (#PCDATA)>

=== nikolaim665/XML-Group-Project/Tickets.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- XML declaration specifying version, encoding, and standalone attribute -->
<!DOCTYPE Tickets SYSTEM "Tickets.dtd">
<!-- Document Type Definition (DTD) declaration -->
<Tickets>
    <!-- Root element, representing a collection of tickets -->
    <Ticket>
        <!-- Start of the first ticket entry -->
        <ticketID>1</ticketID>
        <!-- Ticket ID -->
        <event>1</event>
        <!-- ID of the event associated with the ticket -->
        <customer>1</customer>
        <!-- ID of the customer who owns the ticket -->
    </Ticket>
    <!-- End of the first ticket entry -->
	<!-- ... (similar blocks for the remaining tickets) ... -->
    <Ticket>
        <ticketID>2</ticketID>
        <event>2</event>
        <customer>1</customer>
    </Ticket>
    <Ticket>
        <ticketID>3</ticketID>
        <event>1</event>
        <customer>2</customer>
    </Ticket>
    <Ticket>
        <ticketID>4</ticketID>
        <event>1</event>
        <customer>2</customer>
    </Ticket>
    <Ticket>
        <ticketID>5</ticketID>
        <event>1</event>
        <customer>3</customer>
    </Ticket>
    <Ticket>
        <ticketID>6</ticketID>
        <event>5</event>
        <customer>3</customer>
    </Ticket>
    <Ticket>
        <ticketID>7</ticketID>
        <event>1</event>
        <customer>4</customer>
    </Ticket>
    <Ticket>
        <ticketID>8</ticketID>
        <event>1</event>
        <customer>4</customer>
    </Ticket>
    <Ticket>
        <ticketID>9</ticketID>
        <event>1</event>
        <customer>5</customer>
    </Ticket>
    <Ticket>
        <ticketID>10</ticketID>
        <event>1</event>
        <customer>7</customer>
    </Ticket>
    <Ticket>
        <ticketID>11</ticketID>
        <event>1</event>
        <customer>9</customer>
    </Ticket>
    <Ticket>
        <ticketID>12</ticketID>
        <event>1</event>
        <customer>10</customer>
    </Ticket>
</Tickets>
<!-- End of the root element -->
