=== nikolaim665/XML-Group-Project/Transactions.dtd
<!ELEMENT Transactions (Transaction+)>
<!ELEMENT Transaction (date,platform,paymentMethod,status,savedMethod,ticket)>
<!ATTLIST Transaction 
          id ID #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT paymentMethod (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT savedMethod (#PCDATA)>
<!ELEMENT ticket (ticket_id)>
<!ATTLIST ticekt
          ticket_id ID #REQUIRED>

=== nikolaim665/XML-Group-Project/Transactions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- XML declaration specifying version, encoding, and standalone attribute -->
<!DOCTYPE Transactions SYSTEM "Transactions.dtd">
<!-- Document Type Definition (DTD) declaration -->
<Transactions>
    <!-- Root element, representing a collection of transactions -->
    <Transaction id="1">
        <!-- Start of the first transaction entry with an ID attribute -->
        <date>11/11/2023</date>
        <!-- Date of the transaction -->
        <platform>Paypal/Local</platform>
        <!-- Payment platform used for the transaction -->
        <paymentMethod>mastercard</paymentMethod>
        <!-- Payment method used for the transaction -->
        <status>approved</status>
        <!-- Status of the transaction -->
        <savedMethod>yes</savedMethod>
        <!-- Indicates if the payment method was saved for future use -->
        <ticket>1</ticket>
        <!-- Ticket ID associated with the transaction -->
    </Transaction>
    <!-- End of the first transaction entry -->
    <!-- ... (similar blocks for the remaining transactions) ... -->
    <Transaction id="2">
        <date>11/11/2023</date>
        <platform>Paypal/Local</platform>
        <paymentMethod>visa</paymentMethod>
        <status>declined</status>
        <savedMethod>no</savedMethod>
        <ticket>5</ticket>
    </Transaction>

    <Transaction id="3">
        <date>11/11/2023</date>
        <platform>Paypal/Local</platform>
        <paymentMethod>discover</paymentMethod>
        <status>approved</status>
        <savedMethod>yes</savedMethod>
        <ticket>9</ticket>
    </Transaction>

    <Transaction id="4">
        <date>11/11/2023</date>
        <platform>Paypal/Local</platform>
        <paymentMethod>mastercard</paymentMethod>
        <status>approved</status>
        <savedMethod>yes</savedMethod>
        <ticket>12</ticket>
    </Transaction>
</Transactions>
<!-- End of the root element -->
